### ISSUE TITLE
Error building

### ISSUE THREAD

**Issue by nickkeers** [lambdaclass/erlings#49]
I've checked out the erlings repository and then run make in the top level as instructed, however I do not see the correct output - I get an error as below:

```
... erlings (master) $ make
cd otp/shopping_cart && ../../rebar3 as test  otp/shopping_cart  libraries/shortly  sequential/filter_fibonacci_numbers  sequential/bank_accounts  sequential/hello  sequential/calculate_bmi  sequential/insert_element_at  sequential/filter_numbers  sequential/hello_pattern  sequential/maps  sequential/lists  sequential/installing  distributed/remote_fun  concurrent/ring_benchmark  concurrent/priority  otp  libraries  sequential  distributed  concurrent  ct
===> Command 'otp/shopping_cart' not found
make: *** [Makefile:16: otp/shopping_cart] Error 1
```

Would appreciate any help you can give. Tested with Erlang 18.3 and Erlang 20.1

**Comment by AminArria** [comment]
@nickkeers `make` will run the tests to check your solutions, in your case it started running the ones for the exercise `otp/shopping_cart` and stop because the tests failed.

If you want to run for specific exercises pass de directory, for example for [Installing](https://github.com/lambdaclass/erlings/tree/master/sequential/installing) you would do `make sequential/installing`

**Comment by unbalancedparentheses** [comment]
make test should run all tests. the default target should do something like compile everything or verifying that everything works fine 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nickkeers** [comment]
All sorted, yeah. I was trying to debug an issue someone else was having at the time. Verified it's all fine at home
